#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution testing \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --bootloaders "syslinux grub-efi" \
    --uefi-secure-boot enable \
    --linux-flavours amd64 \
    --linux-packages linux-image \
    --security false \
    --updates false \
    --backports false \
    --memtest none \
    --iso-application "Sensible Live Installer" \
    --iso-publisher "Korq <https://korq.io>" \
    --iso-volume "SENSIBLE_LIVE" \
    --image-name "sensible-debian-testing" \
    --apt-recommends true \
    --bootappend-live "boot=live components console=tty0 console=ttyS0,115200n8" \
    "${@}"
