#!/usr/bin/env bash
# Post-install boot verification: each check must fire on the artifact it owns.
TEST_NAME="verify_test"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/harness.sh"

source "${INSTALLER_DIR}/lib/common.sh"
source "${INSTALLER_DIR}/lib/verify.sh"

WORK="$(mktemp -d /tmp/sensible-verify-test.XXXXXX)"
trap 'rm -rf "${WORK}"' EXIT

# A target that would genuinely boot: kernel, initramfs, signed GRUB on the
# ESP, a grub.cfg with a real entry, and an fstab that mounts / and the ESP.
make_bootable_target() {
    local root="$1"
    rm -rf "${root}"
    mkdir -p "${root}/boot/grub" "${root}/boot/efi/EFI/debian" "${root}/etc"
    touch "${root}/boot/vmlinuz-7.1.0-amd64" "${root}/boot/initrd.img-7.1.0-amd64"
    touch "${root}/boot/efi/EFI/debian/grubx64.efi" "${root}/boot/efi/EFI/debian/shimx64.efi"
    cat > "${root}/boot/grub/grub.cfg" <<'EOF'
menuentry 'Debian GNU/Linux' {
    linux /boot/vmlinuz-7.1.0-amd64 root=UUID=ROOT-UUID ro quiet
    initrd /boot/initrd.img-7.1.0-amd64
}
EOF
    cat > "${root}/etc/fstab" <<'EOF'
UUID=ROOT-UUID  /          ext4  noatime  0 1
UUID=EFI-UUID   /boot/efi  vfat  umask=0077  0 2
EOF
}

T="${WORK}/target"

t_section "a complete install passes"
make_bootable_target "${T}"
validate_installed_boot "${T}" false >/dev/null
assert_rc "bootable target validates" 0 $?

t_section "missing initramfs is caught"
make_bootable_target "${T}"; rm -f "${T}"/boot/initrd.img-*
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "missing initramfs fails validation" 1 "${rc}"
assert_contains "and names the initramfs" "${OUT}" "no initramfs"

t_section "missing EFI binary is caught"
make_bootable_target "${T}"; rm -f "${T}"/boot/efi/EFI/debian/*.efi
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "missing GRUB EFI binary fails validation" 1 "${rc}"
assert_contains "and says firmware would find nothing" "${OUT}" "no GRUB EFI binary"

t_section "shim alone is sufficient (Secure Boot chain)"
make_bootable_target "${T}"; rm -f "${T}/boot/efi/EFI/debian/grubx64.efi"
validate_installed_boot "${T}" false >/dev/null
assert_rc "shimx64 alone still validates" 0 $?

t_section "an entry-less grub.cfg is caught, not just a missing one"
# This is the exact shape of today's failure: the file exists and is non-empty,
# so a file-exists check passes, but GRUB drops to a rescue prompt.
make_bootable_target "${T}"
printf '# generated by grub-mkconfig\nset timeout=5\n' > "${T}/boot/grub/grub.cfg"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "grub.cfg without a menuentry fails" 1 "${rc}"
assert_contains "and names the missing menuentry" "${OUT}" "no menuentry"
assert_contains "and the missing linux line" "${OUT}" "no linux line"

t_section "empty grub.cfg is caught"
make_bootable_target "${T}"; : > "${T}/boot/grub/grub.cfg"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "empty grub.cfg fails" 1 "${rc}"
assert_contains "and mentions the rescue prompt" "${OUT}" "rescue prompt"

t_section "fstab must actually mount / and the ESP"
make_bootable_target "${T}"
printf 'UUID=EFI-UUID /boot/efi vfat umask=0077 0 2\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "fstab without a root entry fails" 1 "${rc}"
assert_contains "and names the root entry" "${OUT}" "no root (/) entry"

make_bootable_target "${T}"
printf 'UUID=ROOT-UUID / ext4 noatime 0 1\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "fstab without an ESP entry fails" 1 "${rc}"
assert_contains "and names /boot/efi" "${OUT}" "/boot/efi"

t_section "a UUID in a comment does not satisfy the fstab check"
make_bootable_target "${T}"
printf '# / was UUID=ROOT-UUID before reinstall\nUUID=EFI-UUID /boot/efi vfat umask=0077 0 2\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "commented-out root entry still fails" 1 "${rc}"

t_section "LUKS requires a crypttab mapping"
make_bootable_target "${T}"
validate_installed_boot "${T}" false >/dev/null
assert_rc "no crypttab is fine when encryption is off" 0 $?

OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "no crypttab fails when encryption is on" 1 "${rc}"
assert_contains "and explains the volume is never unlocked" "${OUT}" "never be unlocked"

printf 'cryptroot UUID=LUKS-UUID none luks,discard\n' > "${T}/etc/crypttab"
validate_installed_boot "${T}" true >/dev/null
assert_rc "a real crypttab mapping validates" 0 $?

printf '# cryptroot UUID=LUKS-UUID none luks\n' > "${T}/etc/crypttab"
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "a commented-out crypttab mapping fails" 1 "${rc}"

t_section "show_failure_screen never blocks a run with no human present"
# The suite itself runs with stdin redirected, so this is the real condition:
# if the guard regressed, this assertion would hang rather than fail, which is
# exactly the outcome the guard exists to prevent in CI and unattended installs.
UI_TOOL="text"
show_failure_screen "partitioning" 1 "/nonexistent/log" </dev/null
assert_rc "returns immediately when stdin is not a terminal" 0 $?

# Belt and braces for a caller that does have a terminal but must not prompt.
SENSIBLE_NO_FAILURE_SCREEN=1 show_failure_screen "partitioning" 1 "/nonexistent/log" </dev/null
assert_rc "explicit opt-out is honoured" 0 $?
unset SENSIBLE_NO_FAILURE_SCREEN

t_summary
