#!/usr/bin/env bash
# Post-install boot verification: each check must fire on the artifact it owns.
TEST_NAME="verify_test"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/harness.sh"

source "${INSTALLER_DIR}/lib/common.sh"
source "${INSTALLER_DIR}/lib/verify.sh"

WORK="$(mktemp -d /tmp/sensible-verify-test.XXXXXX)"
trap 'rm -rf "${WORK}"' EXIT

# A target that would genuinely boot: kernel, initramfs, signed GRUB on the
# ESP, a grub.cfg with a real entry, and an fstab that mounts / and the ESP.
make_bootable_target() {
    local root="$1"
    rm -rf "${root}"
    mkdir -p "${root}/boot/grub" "${root}/boot/efi/EFI/debian" "${root}/etc"
    touch "${root}/boot/vmlinuz-7.1.0-amd64" "${root}/boot/initrd.img-7.1.0-amd64"
    touch "${root}/boot/efi/EFI/debian/grubx64.efi" "${root}/boot/efi/EFI/debian/shimx64.efi"
    cat > "${root}/boot/grub/grub.cfg" <<'EOF'
menuentry 'Debian GNU/Linux' {
    linux /boot/vmlinuz-7.1.0-amd64 root=UUID=ROOT-UUID ro quiet
    initrd /boot/initrd.img-7.1.0-amd64
}
EOF
    cat > "${root}/etc/fstab" <<'EOF'
UUID=ROOT-UUID  /          ext4  noatime  0 1
UUID=EFI-UUID   /boot/efi  vfat  umask=0077  0 2
EOF
}

T="${WORK}/target"

t_section "a complete install passes"
make_bootable_target "${T}"
validate_installed_boot "${T}" false >/dev/null
assert_rc "bootable target validates" 0 $?

t_section "missing initramfs is caught"
make_bootable_target "${T}"; rm -f "${T}"/boot/initrd.img-*
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "missing initramfs fails validation" 1 "${rc}"
assert_contains "and names the initramfs" "${OUT}" "no initramfs"

t_section "missing EFI binary is caught"
make_bootable_target "${T}"; rm -f "${T}"/boot/efi/EFI/debian/*.efi
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "missing GRUB EFI binary fails validation" 1 "${rc}"
assert_contains "and names the missing shim" "${OUT}" "no shimx64.efi"
assert_contains "and names the missing signed GRUB" "${OUT}" "no grubx64.efi"

t_section "the complete signed EFI chain is required"
make_bootable_target "${T}"; rm -f "${T}/boot/efi/EFI/debian/grubx64.efi"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "shim without signed GRUB fails validation" 1 "$rc"
assert_contains "failure explains shim has no second stage" "$OUT" "shim has no signed GRUB"

make_bootable_target "${T}"; rm -f "${T}/boot/efi/EFI/debian/shimx64.efi"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "GRUB without shim fails validation" 1 "$rc"
assert_contains "failure names the missing signed first stage" "$OUT" "no signed first-stage"

t_section "an entry-less grub.cfg is caught, not just a missing one"
# This is the exact shape of today's failure: the file exists and is non-empty,
# so a file-exists check passes, but GRUB drops to a rescue prompt.
make_bootable_target "${T}"
printf '# generated by grub-mkconfig\nset timeout=5\n' > "${T}/boot/grub/grub.cfg"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "grub.cfg without a menuentry fails" 1 "${rc}"
assert_contains "and names the missing menuentry" "${OUT}" "no menuentry"
assert_contains "and the missing linux line" "${OUT}" "no linux line"

t_section "empty grub.cfg is caught"
make_bootable_target "${T}"; : > "${T}/boot/grub/grub.cfg"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "empty grub.cfg fails" 1 "${rc}"
assert_contains "and mentions the rescue prompt" "${OUT}" "rescue prompt"

t_section "fstab must actually mount / and the ESP"
make_bootable_target "${T}"
printf 'UUID=EFI-UUID /boot/efi vfat umask=0077 0 2\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "fstab without a root entry fails" 1 "${rc}"
assert_contains "and names the root entry" "${OUT}" "no root (/) entry"

make_bootable_target "${T}"
printf 'UUID=ROOT-UUID / ext4 noatime 0 1\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "fstab without an ESP entry fails" 1 "${rc}"
assert_contains "and names /boot/efi" "${OUT}" "/boot/efi"

t_section "a UUID in a comment does not satisfy the fstab check"
make_bootable_target "${T}"
printf '# / was UUID=ROOT-UUID before reinstall\nUUID=EFI-UUID /boot/efi vfat umask=0077 0 2\n' > "${T}/etc/fstab"
OUT="$(validate_installed_boot "${T}" false)" && rc=0 || rc=1
assert_rc "commented-out root entry still fails" 1 "${rc}"

t_section "LUKS requires a crypttab mapping"
make_bootable_target "${T}"
validate_installed_boot "${T}" false >/dev/null
assert_rc "no crypttab is fine when encryption is off" 0 $?

OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "no crypttab fails when encryption is on" 1 "${rc}"
assert_contains "and explains the volume is never unlocked" "${OUT}" "never be unlocked"

printf 'cryptroot UUID=LUKS-UUID none luks,discard,initramfs\n' > "${T}/etc/crypttab"
mkdir -p "${T}/etc/cryptsetup-initramfs"
printf 'CRYPTSETUP=y\n' > "${T}/etc/cryptsetup-initramfs/conf-hook"
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "crypttab alone does not substitute for a valid generated initramfs" 1 "${rc}"
assert_contains "and identifies the empty initramfs" "${OUT}" "initramfs is empty"

printf '# cryptroot UUID=LUKS-UUID none luks\n' > "${T}/etc/crypttab"
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "a commented-out crypttab mapping fails" 1 "${rc}"

# Regression (live-copy bug): crypttab without the initramfs option leaves
# early unlock unconfigured -- the exact "cannot unlock at boot" failure.
printf 'cryptroot UUID=LUKS-UUID none luks,discard\n' > "${T}/etc/crypttab"
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "crypttab without the initramfs option fails" 1 "${rc}"
assert_contains "and names the initramfs option" "${OUT}" "initramfs option"

# Build a real (tiny) initramfs so the content gate can be exercised: a newc
# cpio with the given /cryptroot/crypttab text, gzipped, like initramfs-tools
# produces (single member -- unmkinitramfs extracts it to the dir root).
make_initramfs_fixture() {
    local out="$1" crypttab_text="$2" stage
    if ! command -v cpio >/dev/null 2>&1 \
        || ! command -v unmkinitramfs >/dev/null 2>&1; then
        return 1
    fi
    stage=$(mktemp -d)
    mkdir -p "${stage}/cryptroot"
    printf '%s' "${crypttab_text}" > "${stage}/cryptroot/crypttab"
    (cd "${stage}" && find . -print0 | cpio --null -o -H newc 2>/dev/null | gzip > "${out}")
    rm -rf "${stage}"
}

t_section "the initramfs must carry the cryptroot mapping (the prompt vs busybox artifact)"
# The shape of the live-initramfs-stale failure: every binary present, entry
# file present but EMPTY -- exactly what cryptsetup-initramfs ships on a live
# image with no /etc/crypttab, and exactly what boots to busybox silently.
if make_bootable_target "${T}" \
    && printf 'cryptroot UUID=LUKS-UUID none luks,discard,initramfs\n' > "${T}/etc/crypttab" \
    && make_initramfs_fixture "${T}/boot/initrd.img-7.1.0-amd64" \
        'cryptroot UUID=LUKS-UUID none luks,discard,initramfs
'; then
    validate_installed_boot "${T}" true >/dev/null
    assert_rc "initramfs carrying the mapping validates" 0 $?

    make_initramfs_fixture "${T}/boot/initrd.img-7.1.0-amd64" ''
    OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
    assert_rc "EMPTY cryptroot/crypttab inside the initramfs fails" 1 "${rc}"
    assert_contains "and names the busybox outcome" "${OUT}" "busybox"

    make_initramfs_fixture "${T}/boot/initrd.img-7.1.0-amd64" \
        'othermap UUID=OTHER none luks
'
    OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
    assert_rc "initramfs entry for a different mapping fails" 1 "${rc}"

    make_initramfs_fixture "${T}/boot/initrd.img-7.1.0-amd64" \
        'cryptroot UUID=LUKS-UUID none luks,discard,initramfs
'
    rm -f "${T}"/etc/cryptsetup-initramfs/*
    validate_installed_boot "${T}" true >/dev/null
    assert_rc "conf-hook presence is no longer demanded (dead knob since buster)" 0 $?
else
    echo "SKIP: cpio or unmkinitramfs unavailable; initramfs content fixtures not exercised" >&2
fi

# A non-empty file that is not an initramfs is corrupt, even when its mtime is
# fresh. Force the extractor failure so this guard is exercised on hosts that
# do not have initramfs-tools installed too.
make_bootable_target "${T}"
printf 'cryptroot UUID=LUKS-UUID none luks,discard,initramfs\n' > "${T}/etc/crypttab"
printf 'not an initramfs\n' > "${T}/boot/initrd.img-7.1.0-amd64"
unmkinitramfs() { return 1; }
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
unset -f unmkinitramfs
assert_rc "unextractable initramfs fails validation" 1 "$rc"
assert_contains "failure identifies corrupt or truncated image" "$OUT" "corrupt or truncated"

t_section "LUKS target with a stale (un-regenerated) initramfs is rejected"
# This is the screenshot's failure: rsync copied the live initramfs which has
# no cryptsetup, so the target cannot unlock at boot. A real install always
# regenerates the initramfs after de-living, so the initrd mtime is >= kernel.
make_bootable_target "${T}"
printf 'cryptroot UUID=LUKS-UUID none luks,discard,initramfs\n' > "${T}/etc/crypttab"
mkdir -p "${T}/etc/cryptsetup-initramfs"
printf 'CRYPTSETUP=y\n' > "${T}/etc/cryptsetup-initramfs/conf-hook"
# Older than kernel: would mean update-initramfs was skipped (live /run/live
# leaked, update_initramfs=no not flipped, or the script silently no-op'd).
touch -d '2024-01-01' "${T}/boot/vmlinuz-7.1.0-amd64"
touch -d '2024-01-01 00:00:00' "${T}/boot/initrd.img-7.1.0-amd64"
touch -d '2024-01-01 00:01:00' "${T}/boot/vmlinuz-7.1.0-amd64"  # kernel newer
OUT="$(validate_installed_boot "${T}" true)" && rc=0 || rc=1
assert_rc "stale initramfs (older than kernel) fails when LUKS is on" 1 "${rc}"
assert_contains "and points at the live/leak cause" "${OUT}" "was never regenerated"

# Sanity: a fresh, extractable initramfs carrying the mapping passes. Fresh
# timestamps alone are deliberately insufficient now that validation inspects
# the generated image contents.
make_bootable_target "${T}"
printf 'cryptroot UUID=LUKS-UUID none luks,discard,initramfs\n' > "${T}/etc/crypttab"
mkdir -p "${T}/etc/cryptsetup-initramfs"
printf 'CRYPTSETUP=y\n' > "${T}/etc/cryptsetup-initramfs/conf-hook"
if make_initramfs_fixture "${T}/boot/initrd.img-7.1.0-amd64" \
    'cryptroot UUID=LUKS-UUID none luks,discard,initramfs
'; then
    touch "${T}/boot/vmlinuz-7.1.0-amd64"
    touch "${T}/boot/initrd.img-7.1.0-amd64"
    validate_installed_boot "${T}" true >/dev/null
    assert_rc "fresh initramfs carrying the mapping validates" 0 $?
else
    echo "SKIP: cpio or unmkinitramfs unavailable; fresh initramfs fixture not exercised" >&2
fi

t_section "show_failure_screen never blocks a run with no human present"
# The suite itself runs with stdin redirected, so this is the real condition:
# if the guard regressed, this assertion would hang rather than fail, which is
# exactly the outcome the guard exists to prevent in CI and unattended installs.
UI_TOOL="text"
show_failure_screen "partitioning" 1 "/nonexistent/log" </dev/null
assert_rc "returns immediately when stdin is not a terminal" 0 $?

# Belt and braces for a caller that does have a terminal but must not prompt.
SENSIBLE_NO_FAILURE_SCREEN=1 show_failure_screen "partitioning" 1 "/nonexistent/log" </dev/null
assert_rc "explicit opt-out is honoured" 0 $?
unset SENSIBLE_NO_FAILURE_SCREEN

t_summary
